-- Supabase SQL schema for Pepper resource pack uploads
-- Create a storage bucket for ZIP uploads.
-- If this fails, create the bucket directly in the Supabase Dashboard Storage panel.
insert into storage.buckets (id, name)
values ('packs', 'packs')
on conflict (id) do nothing;

-- Create a packs metadata table
CREATE TABLE IF NOT EXISTS packs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    author TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    fullDescription TEXT,
    version TEXT,
    downloads INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    cover TEXT,
    gallery JSONB DEFAULT '[]'::jsonb,
    versions JSONB DEFAULT '[]'::jsonb,
    uploadedBy TEXT,
    featured BOOLEAN DEFAULT FALSE,
    uploadDate TIMESTAMPTZ DEFAULT NOW(),
    tags TEXT[] DEFAULT '{}',
    compatibility TEXT[] DEFAULT '{}',
    rating NUMERIC(3,2) DEFAULT 0,
    downloads_all_time INTEGER DEFAULT 0,
    downloadUrl TEXT,
    filePath TEXT
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    liked_packs JSONB DEFAULT '[]'::jsonb,
    uploaded_packs JSONB DEFAULT '[]'::jsonb
);
