-- Supabase SQL schema for Pepper resource pack uploads
-- Create a public storage bucket for ZIP uploads.
-- If this fails, create the bucket directly in the Supabase Dashboard Storage panel.
insert into storage.buckets (id, name, public)
values ('packs', 'packs', true)
on conflict (id) do update set public = excluded.public, name = excluded.name;

-- Create a packs metadata table
CREATE TABLE IF NOT EXISTS packs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    author TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    "fullDescription" TEXT,
    version TEXT,
    downloads INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    cover TEXT,
    gallery JSONB DEFAULT '[]'::jsonb,
    versions JSONB DEFAULT '[]'::jsonb,
    "uploadedBy" TEXT,
    featured BOOLEAN DEFAULT FALSE,
    "uploadDate" TIMESTAMPTZ DEFAULT NOW(),
    tags TEXT[] DEFAULT '{}',
    compatibility TEXT[] DEFAULT '{}',
    rating NUMERIC(3,2) DEFAULT 0,
    downloads_all_time INTEGER DEFAULT 0,
    "downloadUrl" TEXT,
    "filePath" TEXT
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    liked_packs JSONB DEFAULT '[]'::jsonb,
    uploaded_packs JSONB DEFAULT '[]'::jsonb,
    display_name TEXT,
    bio TEXT,
    avatar_url TEXT,
    website TEXT
);

-- Add profile columns if they don't exist (for existing databases)
ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS website TEXT;
