-- Supabase SQL schema for Pepper resource pack uploads
-- Create a public storage bucket for ZIP uploads.
-- If this fails, create the bucket directly in the Supabase Dashboard Storage panel.
insert into storage.buckets (id, name, public)
values ('packs', 'packs', true)
on conflict (id) do update set public = excluded.public, name = excluded.name;

-- Create a packs metadata table
CREATE TABLE IF NOT EXISTS packs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    author TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    "fullDescription" TEXT,
    version TEXT,
    downloads INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    cover TEXT,
    gallery JSONB DEFAULT '[]'::jsonb,
    versions JSONB DEFAULT '[]'::jsonb,
    "uploadedBy" TEXT,
    featured BOOLEAN DEFAULT FALSE,
    "uploadDate" TIMESTAMPTZ DEFAULT NOW(),
    tags TEXT[] DEFAULT '{}',
    compatibility TEXT[] DEFAULT '{}',
    rating NUMERIC(3,2) DEFAULT 0,
    downloads_all_time INTEGER DEFAULT 0,
    "downloadUrl" TEXT,
    "filePath" TEXT
);

-- Enable row-level security for pack metadata and allow anonymous clients to access packs.
ALTER TABLE packs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon select on packs" ON packs;
CREATE POLICY "Allow anon select on packs"
    ON packs FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow anon insert on packs" ON packs;
CREATE POLICY "Allow anon insert on packs"
    ON packs FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon update on packs" ON packs;
CREATE POLICY "Allow anon update on packs"
    ON packs FOR UPDATE
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon delete on packs" ON packs;
CREATE POLICY "Allow anon delete on packs"
    ON packs FOR DELETE
    USING (true);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    liked_packs JSONB DEFAULT '[]'::jsonb,
    uploaded_packs JSONB DEFAULT '[]'::jsonb,
    display_name TEXT,
    bio TEXT,
    avatar_url TEXT,
    website TEXT
);

-- Add profile columns if they don't exist (for existing databases)
ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS website TEXT;

-- Enable row-level security with policies for browser access.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Allow anonymous web clients to read and write user rows.
-- This is a simple policy for the current app's browser-based auth flow.
DROP POLICY IF EXISTS "Allow anon select on users" ON users;
CREATE POLICY "Allow anon select on users"
    ON users FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow anon insert on users" ON users;
CREATE POLICY "Allow anon insert on users"
    ON users FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon update on users" ON users;
CREATE POLICY "Allow anon update on users"
    ON users FOR UPDATE
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon delete on users" ON users;
CREATE POLICY "Allow anon delete on users"
    ON users FOR DELETE
    USING (true);
